In [1]:
import haversine as hs   
from haversine import Unit

In [2]:
commune_list = ["Anniviers", "Chalais", "Chippis", "Crans-Montana", "Grône", "Icogne", "Lens", "Noble-Contrée", "Saint-Léonard", "Sierre"]
pts_list = [(46.183056, 7.598889), (46.265556, 7.507222), (46.281944, 7.544444), (46.311944, 7.482778), (46.253056, 7.458889), (46.292500, 7.440278), (46.278889, 7.445000), (46.312500, 7.548333), (46.250000, 7.416667), (46.293056, 7.533056)]

len(commune_list), len(pts_list)

(10, 10)

In [3]:
import pandas as pd
df = pd.DataFrame(index=commune_list)

for i in range(len(commune_list)):
    liste = [hs.haversine(pts_list[i],pts_list[j],unit=Unit.KILOMETERS) for j in range(len(commune_list))]
    df[commune_list[i]] = liste

df

,Anniviers,Chalais,Chippis,Crans-Montana,Grône,Icogne,Lens,Noble-Contrée,Saint-Léonard,Sierre
Anniviers,0.000000,11.570791,11.766320,16.885382,13.289296,17.231069,15.927012,14.909289,15.873699,13.237992
Chalais,11.570791,0.000000,3.391932,5.489441,3.967283,5.953580,5.007014,6.101343,7.173709,3.645861
Chippis,11.766320,3.391932,0.000000,5.794213,7.319029,8.089789,7.649837,3.410788,10.444802,1.514078
Crans-Montana,16.885382,5.489441,5.794213,0.000000,6.800530,3.915829,4.683366,5.035369,8.558921,4.396425
Grône,13.289296,3.967283,7.319029,6.800530,0.000000,4.613352,3.064499,9.536005,3.264215,7.230409
Icogne,17.231069,5.953580,8.089789,3.915829,4.613352,0.000000,1.556365,8.593448,5.062277,7.128667
Lens,15.927012,5.007014,7.649837,4.683366,3.064499,1.556365,0.000000,8.774671,3.881080,6.947388
Noble-Contrée,14.909289,6.101343,3.410788,5.035369,9.536005,8.593448,8.774671,0.000000,12.275189,2.460045
Saint-Léonard,15.873699,7.173709,10.444802,8.558921,3.264215,5.062277,3.881080,12.275189,0.000000,10.146506
Sierre,13.237992,3.645861,1.514078,4.396425,7.230409,7.128667,6.947388,2.460045,10.146506,0.000000

In [5]:
warehouse_loc = (46.281778, 7.512944)
liste = [hs.haversine(warehouse_loc,pts_list[j],unit=Unit.KILOMETERS) for j in range(len(commune_list))]
df["Warehouse"] = liste

df

,Anniviers,Chalais,Chippis,Crans-Montana,Grône,Icogne,Lens,Noble-Contrée,Saint-Léonard,Sierre,Warehouse
Anniviers,0.000000,11.570791,11.766320,16.885382,13.289296,17.231069,15.927012,14.909289,15.873699,13.237992,12.814222
Chalais,11.570791,0.000000,3.391932,5.489441,3.967283,5.953580,5.007014,6.101343,7.173709,3.645861,1.856646
Chippis,11.766320,3.391932,0.000000,5.794213,7.319029,8.089789,7.649837,3.410788,10.444802,1.514078,2.420788
Crans-Montana,16.885382,5.489441,5.794213,0.000000,6.800530,3.915829,4.683366,5.035369,8.558921,4.396425,4.077072
Grône,13.289296,3.967283,7.319029,6.800530,0.000000,4.613352,3.064499,9.536005,3.264215,7.230409,5.240711
Icogne,17.231069,5.953580,8.089789,3.915829,4.613352,0.000000,1.556365,8.593448,5.062277,7.128667,5.709575
Lens,15.927012,5.007014,7.649837,4.683366,3.064499,1.556365,0.000000,8.774671,3.881080,6.947388,5.231390
Noble-Contrée,14.909289,6.101343,3.410788,5.035369,9.536005,8.593448,8.774671,0.000000,12.275189,2.460045,4.366002
Saint-Léonard,15.873699,7.173709,10.444802,8.558921,3.264215,5.062277,3.881080,12.275189,0.000000,10.146506,8.201150
Sierre,13.237992,3.645861,1.514078,4.396425,7.230409,7.128667,6.947388,2.460045,10.146506,0.000000,1.990217

In [ ]:
df.to_excel("distances.xlsx")

In [ ]:
alts_list = ["848/1691", "522/1330", "526/532", "577/1546", "503/1064", "1034/1160", "758/1637", "600/907", "500/507", "500/559"]

for i in range(len(commune_list)):
    alt = alts_list[i].split("/")
    
    alt = [int(x) for x in alt]
    df.loc[commune_list[i], "Altitude"] = alt[0]
    df.loc[commune_list[i], "Max Altitude"] = alt[1]

In [4]:
import pandas as pd

df = pd.read_excel("distances.xlsx", index_col=0)
df

,Anniviers,Chalais,Chippis,Crans-Montana,Grône,Icogne,Lens,Noble-Contrée,Saint-Léonard,Sierre,Warehouse
Anniviers,7.185000,11.570791,11.766320,16.885382,13.289296,17.231069,15.927012,14.909289,15.873699,13.237992,12.814222
Chalais,11.570791,1.055000,3.391932,5.489441,3.967283,5.953580,5.007014,6.101343,7.173709,3.645861,1.856646
Chippis,11.766320,3.391932,0.186000,5.794213,7.319029,8.089789,7.649837,3.410788,10.444802,1.514078,2.420788
Crans-Montana,16.885382,5.489441,5.794213,2.893000,6.800530,3.915829,4.683366,5.035369,8.558921,4.396425,4.077072
Grône,13.289296,3.967283,7.319029,6.800530,0.736000,4.613352,3.064499,9.536005,3.264215,7.230409,5.240711
Icogne,17.231069,5.953580,8.089789,3.915829,4.613352,0.880000,1.556365,8.593448,5.062277,7.128667,5.709575
Lens,15.927012,5.007014,7.649837,4.683366,3.064499,1.556365,2.595000,8.774671,3.881080,6.947388,5.231390
Noble-Contrée,14.909289,6.101343,3.410788,5.035369,9.536005,8.593448,8.774671,0.945000,12.275189,2.460045,4.366002
Saint-Léonard,15.873699,7.173709,10.444802,8.558921,3.264215,5.062277,3.881080,12.275189,1.110000,10.146506,8.201150
Sierre,13.237992,3.645861,1.514078,4.396425,7.230409,7.128667,6.947388,2.460045,10.146506,4.950000,1.990217

In [11]:
df.loc["Anniviers", "Chippis"]

np.float64(11.76632007463956)

In [12]:
import numpy.random as npr

radius = df.loc["Anniviers", "Anniviers"]
print(int(radius/2*1000), int(radius*1000))
npr.random_integers(low = int(radius/2*1000), high = int(radius*1000))/1000

3592 7185

C:\Users\Julien\AppData\Local\Temp\ipykernel_34364\3927246082.py:5: DeprecationWarning: This function is deprecated. Please call randint(3592, 7185 + 1) instead
  npr.random_integers(low = int(radius/2*1000), high = int(radius*1000))/1000

np.float64(4.486)

In [2]:
import pandas as pd
df = pd.read_excel("distances.xlsx", index_col=0)

df

,Anniviers,Chalais,Chippis,Crans-Montana,Grône,Icogne,Lens,Noble-Contrée,Saint-Léonard,Sierre,Warehouse
Anniviers,7.185000,11.570791,11.766320,16.885382,13.289296,17.231069,15.927012,14.909289,15.873699,13.237992,12.814222
Chalais,11.570791,1.055000,3.391932,5.489441,3.967283,5.953580,5.007014,6.101343,7.173709,3.645861,1.856646
Chippis,11.766320,3.391932,0.186000,5.794213,7.319029,8.089789,7.649837,3.410788,10.444802,1.514078,2.420788
Crans-Montana,16.885382,5.489441,5.794213,2.893000,6.800530,3.915829,4.683366,5.035369,8.558921,4.396425,4.077072
Grône,13.289296,3.967283,7.319029,6.800530,0.736000,4.613352,3.064499,9.536005,3.264215,7.230409,5.240711
Icogne,17.231069,5.953580,8.089789,3.915829,4.613352,0.880000,1.556365,8.593448,5.062277,7.128667,5.709575
Lens,15.927012,5.007014,7.649837,4.683366,3.064499,1.556365,2.595000,8.774671,3.881080,6.947388,5.231390
Noble-Contrée,14.909289,6.101343,3.410788,5.035369,9.536005,8.593448,8.774671,0.945000,12.275189,2.460045,4.366002
Saint-Léonard,15.873699,7.173709,10.444802,8.558921,3.264215,5.062277,3.881080,12.275189,1.110000,10.146506,8.201150
Sierre,13.237992,3.645861,1.514078,4.396425,7.230409,7.128667,6.947388,2.460045,10.146506,4.950000,1.990217

In [8]:
altitudes = pd.DataFrame()

alts = ["848/1691", "522/1330", "526/532" , "626/1546", "503/1064", "1034/1160", "626/1648", "600/907", "500/550", "500/559"]

for i in range(len(df.columns)-1):
    altitudes[df.columns[i]] = [int(x) for x in alts[i].split("/")]

altitudes

,Anniviers,Chalais,Chippis,Crans-Montana,Grône,Icogne,Lens,Noble-Contrée,Saint-Léonard,Sierre
0,848,522,526,626,503,1034,626,600,500,500
1,1691,1330,532,1546,1064,1160,1648,907,550,559

In [13]:
c_i = pd.read_excel("communes_infos.xlsx", index_col=0)

c_i

,Anniviers,Chalais,Chippis,Crans-Montana,Grône,Icogne,Lens,Noble-Contrée,Saint-Léonard,Sierre
Commune,,,,,,,,,,
Radius,7185,1055,186,2893,736,880,2595,945,1110,4950
Citizens,2790,3927,1615,10496,2556,640,4570,4693,2628,17829
Density,11,161,816,176,121,26,329,721,674,930

In [14]:
df = pd.read_excel("altitudes.xlsx", index_col=0)

df

,Anniviers,Chalais,Chippis,Crans-Montana,Grône,Icogne,Lens,Noble-Contrée,Saint-Léonard,Sierre
0,848,522,526,626,503,1034,626,600,500,500
1,1691,1330,532,1546,1064,1160,1648,907,550,559

In [15]:
df.index = ["min", "max"]
df

,Anniviers,Chalais,Chippis,Crans-Montana,Grône,Icogne,Lens,Noble-Contrée,Saint-Léonard,Sierre
min,848,522,526,626,503,1034,626,600,500,500
max,1691,1330,532,1546,1064,1160,1648,907,550,559

In [16]:
df.to_excel("altitudes.xlsx")

In [4]:
import pandas as pd

df = pd.read_csv("hourly_share_of_daily_demand.csv", index_col=0)
df

,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,sum check
Day,,,,,,,,,,,,,,,,
Monday,0.014244,0.091127,0.121990,0.116121,0.101782,0.065961,0.063150,0.066170,0.093710,0.094963,0.074793,0.058003,0.029439,0.008547,0.000000,1
Tuesdasy,0.007947,0.079539,0.105516,0.093386,0.081527,0.056211,0.061139,0.070039,0.103648,0.108441,0.100201,0.080917,0.040362,0.011126,0.000000,1
Wednesday,0.010731,0.081911,0.112080,0.103407,0.085752,0.057575,0.066469,0.074206,0.101954,0.097276,0.085807,0.068351,0.040449,0.014033,0.000000,1
Thursday,0.007926,0.085804,0.112023,0.105688,0.089659,0.053598,0.053693,0.060034,0.089858,0.096982,0.094809,0.083453,0.045865,0.020607,0.000000,1
Friday,0.009466,0.062930,0.089586,0.086535,0.073997,0.047437,0.044645,0.054738,0.082101,0.110892,0.117951,0.098802,0.073872,0.035215,0.011833,1
Saturday,0.008689,0.058849,0.087440,0.101702,0.092376,0.068665,0.066505,0.062395,0.082092,0.095927,0.096982,0.081815,0.059407,0.029490,0.007667,1
Sunday,0.006633,0.060557,0.087936,0.103775,0.099504,0.067680,0.073623,0.075414,0.097766,0.105606,0.096891,0.080747,0.035909,0.007959,0.000000,1

In [6]:
df.loc["Monday"]["13"]

0.116120945

In [ ]:
import numpy as np
commune_info_df = pd.read_csv("weekly_daily_demand.csv", index_col=0)
hourly_share_of_daily_demand = df.loc["Tueasd"]["13"]
demand_per_commune = commune_info_df.loc[:, "demand_"+"Monday"].to_numpy()*commune_info_df.loc[:, "weekly_fast_food_demand"].to_numpy()/commune_info_df.loc[:, "weekly_demand"].to_numpy()
hourly_demand = hourly_share_of_daily_demand * demand_per_commune
threshold_fct = np.vectorize(lambda x: x if x >= 7 else 0)
hourly_demand = threshold_fct(hourly_demand)
hourly_demand, hourly_demand.shape

(array([ 0,  9,  0, 25,  0,  0, 11, 11,  0, 43]), (10,))

In [1]:
import pandas as pd
altitudes = pd.read_excel("altitudes.xlsx", index_col=0)
altitudes

,Anniviers,Chalais,Chippis,Crans-Montana,Grône,Icogne,Lens,Noble-Contrée,Saint-Léonard,Sierre
min,848,522,526,626,503,1034,626,600,500,500
max,1691,1330,532,1546,1064,1160,1648,907,550,559

In [3]:
altitudes.loc["min", "Sierre"]

500