In [1]:
import haversine as hs   
from haversine import Unit

In [2]:
commune_list = ["Anniviers", "Chalais", "Chippis", "Crans-Montana", "Grône", "Icogne", "Lens", "Noble-Contrée", "Saint-Léonard", "Sierre"]
pts_list = [(46.183056, 7.598889), (46.265556, 7.507222), (46.281944, 7.544444), (46.311944, 7.482778), (46.253056, 7.458889), (46.292500, 7.440278), (46.278889, 7.445000), (46.312500, 7.548333), (46.250000, 7.416667), (46.293056, 7.533056)]

len(commune_list), len(pts_list)

(10, 10)

In [3]:
import pandas as pd
df = pd.DataFrame(index=commune_list)

for i in range(len(commune_list)):
    liste = [hs.haversine(pts_list[i],pts_list[j],unit=Unit.KILOMETERS) for j in range(len(commune_list))]
    df[commune_list[i]] = liste

df

,Anniviers,Chalais,Chippis,Crans-Montana,Grône,Icogne,Lens,Noble-Contrée,Saint-Léonard,Sierre
Anniviers,0.000000,11.570791,11.766320,16.885382,13.289296,17.231069,15.927012,14.909289,15.873699,13.237992
Chalais,11.570791,0.000000,3.391932,5.489441,3.967283,5.953580,5.007014,6.101343,7.173709,3.645861
Chippis,11.766320,3.391932,0.000000,5.794213,7.319029,8.089789,7.649837,3.410788,10.444802,1.514078
Crans-Montana,16.885382,5.489441,5.794213,0.000000,6.800530,3.915829,4.683366,5.035369,8.558921,4.396425
Grône,13.289296,3.967283,7.319029,6.800530,0.000000,4.613352,3.064499,9.536005,3.264215,7.230409
Icogne,17.231069,5.953580,8.089789,3.915829,4.613352,0.000000,1.556365,8.593448,5.062277,7.128667
Lens,15.927012,5.007014,7.649837,4.683366,3.064499,1.556365,0.000000,8.774671,3.881080,6.947388
Noble-Contrée,14.909289,6.101343,3.410788,5.035369,9.536005,8.593448,8.774671,0.000000,12.275189,2.460045
Saint-Léonard,15.873699,7.173709,10.444802,8.558921,3.264215,5.062277,3.881080,12.275189,0.000000,10.146506
Sierre,13.237992,3.645861,1.514078,4.396425,7.230409,7.128667,6.947388,2.460045,10.146506,0.000000

In [5]:
warehouse_loc = (46.281778, 7.512944)
liste = [hs.haversine(warehouse_loc,pts_list[j],unit=Unit.KILOMETERS) for j in range(len(commune_list))]
df["Warehouse"] = liste

df

,Anniviers,Chalais,Chippis,Crans-Montana,Grône,Icogne,Lens,Noble-Contrée,Saint-Léonard,Sierre,Warehouse
Anniviers,0.000000,11.570791,11.766320,16.885382,13.289296,17.231069,15.927012,14.909289,15.873699,13.237992,12.814222
Chalais,11.570791,0.000000,3.391932,5.489441,3.967283,5.953580,5.007014,6.101343,7.173709,3.645861,1.856646
Chippis,11.766320,3.391932,0.000000,5.794213,7.319029,8.089789,7.649837,3.410788,10.444802,1.514078,2.420788
Crans-Montana,16.885382,5.489441,5.794213,0.000000,6.800530,3.915829,4.683366,5.035369,8.558921,4.396425,4.077072
Grône,13.289296,3.967283,7.319029,6.800530,0.000000,4.613352,3.064499,9.536005,3.264215,7.230409,5.240711
Icogne,17.231069,5.953580,8.089789,3.915829,4.613352,0.000000,1.556365,8.593448,5.062277,7.128667,5.709575
Lens,15.927012,5.007014,7.649837,4.683366,3.064499,1.556365,0.000000,8.774671,3.881080,6.947388,5.231390
Noble-Contrée,14.909289,6.101343,3.410788,5.035369,9.536005,8.593448,8.774671,0.000000,12.275189,2.460045,4.366002
Saint-Léonard,15.873699,7.173709,10.444802,8.558921,3.264215,5.062277,3.881080,12.275189,0.000000,10.146506,8.201150
Sierre,13.237992,3.645861,1.514078,4.396425,7.230409,7.128667,6.947388,2.460045,10.146506,0.000000,1.990217

In [7]:
df.to_excel("temp.xlsx")